"""Source-linked presets. Adaptations are explicit, never labeled exact replications."""
SOURCES={
 'muse2017':{'title':'Krigolson et al. (2017), Choosing MUSE','url':'https://pmc.ncbi.nlm.nih.gov/articles/PMC5344886/'},
 'core':{'title':'Kappenman et al. (2021), ERP CORE','url':'https://erpinfo.org/erp-core'},
 'n170':{'title':'Luck, Design of the N170 Experiment (ERP CORE)','url':'https://socialsci.libretexts.org/Bookshelves/Psychology/Biological_Psychology/Applied_Event-Related_Potential_Data_Analysis_(Luck)/11%3A_EEGLAB_and_ERPLAB_Scripting/11.04%3A_Design_of_the_N170_Experiment'},
 'expertise':{'title':'Rossion et al. (2007), expertise and N170','url':'https://pubmed.ncbi.nlm.nih.gov/17335400/'},
 'theta':{'title':'Gärtner et al. (2015), frontal theta and arithmetic','url':'https://pmc.ncbi.nlm.nih.gov/articles/PMC4403551/'},
 'alpha':{'title':'Ishii et al. (2014), rest and mental calculation','url':'https://pmc.ncbi.nlm.nih.gov/articles/PMC4052629/'},
 'muse_specs':{'title':'Muse official headset specifications','url':'https://choosemuse.my.site.com/s/article/Comparing-Muse-Headbands?language=en_US'}
}
PROTOCOLS=[
 dict(id='oddball',mode='erp',title='Visual oddball · P300',tag='RECOMMENDED FIRST ERP',component='P300 / N200',description='Count rare blue circles among frequent green circles.',conditions=['Standard','Target'],channels=['TP9','TP10'],window=[.30,.50],polarity='positive',trials=120,stim_ms=[800,1200],isi_ms=[300,500],probability=.25,source=['muse2017'],ready=True,notes='Recommended first ERP: silently count rare blue circles. Use pooled TP9/TP10 relative to the recorded Fpz reference; compare target minus standard mean amplitude at 300–500 ms. Begin with 120 trials (~3 minutes); 25% are targets, so artifact rejection may leave too few usable targets. If needed, choose 240 trials before starting. Take the scheduled breaks every 40 trials. A clear single-person P300 is not guaranteed. Source timing, RGB colors and 25% targets. Teaching adaptation: 256 Hz Muse 2, -200 ms baseline, causal .1–30 Hz filter. Source used older Muse hardware and different preprocessing. Circle visual angle is configurable; original numerical size is not specified in the accessible methods. P300 is usually maximal at Pz, absent on Muse; TP9/TP10 pooling follows the Muse validation.'),
 dict(id='auditory',mode='erp',title='Auditory oddball',tag='AUDITORY',component='N1 / P300',description='Count higher tones: 1000 Hz standard, 1500 Hz target.',conditions=['Standard','Target'],channels=['AF7','AF8'],window=[.30,.60],polarity='positive',trials=160,stim_ms=[100,100],isi_ms=[1100,1300],probability=.20,source=['core'],ready=True,notes='Conventional frequency-oddball teaching adaptation; not the ERP CORE intensity-MMN protocol. Equal digital amplitude, 5 ms ramps, 100 ms tones. Speaker output is not calibrated dB SPL. Canonical auditory maxima are frontocentral (Fz/Cz); Muse AF7/AF8 are lateral proxies.'),
 dict(id='faces',mode='erp',title='Faces & cars',tag='IMAGE SET',component='N170',description='Compare intact faces and cars using a documented image set.',conditions=['Faces','Cars'],channels=['TP9','TP10'],window=[.11,.20],polarity='negative',trials=160,stim_ms=[300,300],isi_ms=[1100,1300],probability=.5,source=['core','n170'],ready=False,notes='Import at least 20 distinct images per category with provenance. ERP CORE uses 40 per category and scrambled controls with object/texture judgments; this two-condition comparison is an adaptation. N170 is usually measured at P7/P8/PO7/PO8, absent on Muse. Detection is uncertain at TP9/TP10.'),
 dict(id='expertise',mode='erp',title='Objects of expertise',tag='IMAGE SET',component='N170 / N250',description='Compare the categories you know best and least well.',conditions=['Experienced','Unfamiliar'],channels=['TP9','TP10'],window=[.13,.20],polarity='negative',trials=160,stim_ms=[300,300],isi_ms=[1100,1300],probability=.5,source=['expertise'],ready=False,notes='Exploratory adaptation; self-rating is not an objective expertise test. Birds, dog breeds, car models, food, plants, musical instruments, aircraft and chess positions are supported categories. Food and other extensions are not claimed to replicate the cited car study. Match exemplar counts and visual controls; canonical occipitotemporal sites are absent.'),
 dict(id='flanker',mode='erp',title='Flanker conflict',tag='RESPONSE TASK',component='Stimulus-locked N2',description='Use left/right arrows to report the middle arrow, ignoring flankers.',conditions=['Congruent','Incongruent'],channels=['AF7','AF8'],window=[.20,.35],polarity='negative',trials=120,stim_ms=[200,200],isi_ms=[1200,1400],probability=.5,source=['core'],ready=True,notes='Teaching adaptation. Records responses, accuracy and reaction times. This measures stimulus-locked conflict; it does not claim to measure response-locked ERN. Canonical FCz is absent; frontal Muse channels are proxies.'),
 dict(id='reward',mode='erp',title='Reward feedback',tag='FRONTAL',component='Reward positivity',description='Choose a square with left/right arrows; compare win and loss feedback.',conditions=['Loss','Win'],channels=['AF7','AF8'],window=[.25,.35],polarity='positive',trials=100,stim_ms=[1000,1000],isi_ms=[300,500],probability=.5,source=['muse2017'],ready=True,notes='Feedback-locked teaching adaptation. Blue/green choices have .60/.10 reward probability; positions randomized. AF7/AF8 are re-referenced to TP9/TP10 average for this task. Original block color changes are omitted; canonical FCz is absent.'),
 dict(id='alpha',mode='tf',title='Eyes open & closed',tag='ALPHA · 8–13 Hz',component='Alpha power',description='Alternate short rest blocks with eyes open and closed. Audio cues signal each block.',conditions=['Eyes open','Eyes closed'],channels=['TP9','TP10'],window=[2.,8.],band=[8,13],polarity='positive',trials=20,stim_ms=[8000,8000],isi_ms=[2000,2000],probability=.5,source=['alpha'],ready=True,notes='Classical alpha reactivity teaching adaptation. Posterior maxima O1/O2 are absent on Muse; temporal alpha may be detectable. Exclude transitions in first 2 s; compare nonoverlapping block-level power.'),
 dict(id='theta',mode='tf',title='Rest & mental arithmetic',tag='THETA · 4–7 Hz',component='Theta power',description='Rest or silently subtract seven repeatedly from the displayed number.',conditions=['Rest','Arithmetic'],channels=['AF7','AF8'],window=[2.,8.],band=[4,7],polarity='positive',trials=20,stim_ms=[8000,8000],isi_ms=[2000,2000],probability=.5,source=['theta'],ready=True,notes='Exploratory block adaptation; keep eyes open in both conditions. Frontal midline Fz is absent on Muse. Lateral frontal estimates are sensitive to ocular contamination.'),
 dict(id='custom',mode='tf',title='Your own conditions',tag='CUSTOM',component='Band power',description='Name two naturalistic conditions and define your frequency band.',conditions=['Meditation','Lecture questions'],channels=['AF7','AF8'],window=[2.,8.],band=[8,13],polarity='positive',trials=20,stim_ms=[8000,8000],isi_ms=[2000,2000],probability=.5,source=[],ready=True,notes='User-designed exploratory task. Movement, speech, eye state, sound level and lighting can confound differences. No expected neural effect is implied.'),
 dict(id='biofeedback',mode='bio',title='Alpha training & behavior',tag='TRAIN + MEASURE',component='Alpha power',description='Math pretest → resting baseline → alpha feedback → resting posttest → math posttest.',conditions=['Before','After'],channels=['TP9','TP10'],window=[2.,8.],band=[8,13],polarity='positive',trials=20,stim_ms=[8000,8000],isi_ms=[2000,2000],probability=.5,source=['alpha'],ready=True,notes='Exploratory within-person training. Reports alpha-power change and math accuracy/speed. Pre/post differences do not establish training efficacy: practice, fatigue and time are uncontrolled. Feedback freezes during artifacts.'),
]
