const fs=require('fs'),vm=require('vm'),assert=require('assert');const source=fs.readFileSync(__dirname+'/../web/app.js','utf8');
async function main(){
 const nodes=new Map(),$=id=>{if(!nodes.has(id))nodes.set(id,{textContent:'',disabled:false,open:true,close(){this.open=false}});return nodes.get(id)};
 let starts=0;const box={$,selectedResult:null,previewReviewWindow:null,updateResultExports(){},AudioContext:function(){this.resume=async()=>{}},audioCtx:null,syncClock:async()=>{vm.runInContext('preflightOverride=false',box)},config:()=>({channels:['TP10'],calibration:{distance_cm:60,screen_width_cm:30,visual_angle_deg:5}}),api:async(path,c)=>{assert.equal(path,'start');assert.equal(c.allow_noisy_start,true);starts++;return {source:'live'}},active:false,runID:0,sessionStart:0,show(){},buildProtocols(){},participantInstruction:()=>'',protocol:{id:'oddball'},fixation:async()=>{throw Error('cancelled')},renderPreflight(){},toast(){throw Error('Unexpected toast')},Date};vm.createContext(box);vm.runInContext(source.slice(source.indexOf('let preflightOverride='),source.indexOf('async function endRun')),box);vm.runInContext('preflightOverride=true',box);await vm.runInContext('beginRun()',box);assert.equal(starts,1);assert.equal($('preflight').open,false);
 const widths=[];const ctx=new Proxy({}, {get:()=>()=>{},set:()=>true});box.state={session:{minimum:10}};box.colors=['green','orange'];box.axes=()=>({ctx,x:v=>v,y:v=>v,box:{l:0,t:0,r:500,b:250}});box.line=(c,p,color,width)=>widths.push(width);box.text=()=>{};
 vm.runInContext(source.slice(source.indexOf('function drawERP('),source.indexOf('function drawLiveERPs(')),box);
 const group=n=>({accepted:n,recent:[{wave:[1,2]}],erp:{mean:[1,2],ci95:[.1,.2]},label:'Target'});
 box.data={times:[0,.4],groups:[group(1)]};vm.runInContext("drawERP('test',data)",box);assert(!widths.includes(2));widths.length=0;box.data.groups=[group(10)];vm.runInContext("drawERP('test',data)",box);assert(widths.includes(2));console.log('One-click noisy-start approval survives changing contact; trials appear before average threshold, averages at threshold.');
}main().catch(e=>{console.error(e);process.exit(1)});
