/* Account dialogs are separate from opt-in research settings. No automatic uploads. */
async function initEnrollment(){
 const el=id=>document.getElementById(id);
 const dialogs=[];
 function screen(id,title,body){const d=document.createElement('dialog');d.id=id;d.className='account-screen';d.setAttribute('aria-labelledby',id+'Title');d.innerHTML=`<button type="button" class="dialog-close" aria-label="Close ${title}">×</button><h2 id="${id}Title">${title}</h2>${body}`;d.querySelector('.dialog-close').onclick=()=>d.close();document.body.append(d);dialogs.push(d);return d}
 const label=(text,id,type='text',auto='off')=>`<label>${text}<input id="${id}" type="${type}" autocomplete="${auto}" required ${type==='password'?'minlength="8"':''}></label>`;
 const message=id=>`<p id="${id}" role="status" aria-live="polite" class="form-message"></p>`;
 const remember=id=>`<label class="check-label"><input id="${id}" type="checkbox" checked> Keep me signed in on this computer</label>`;
 const login=screen('loginScreen','Sign in',`<form id="loginForm">${label('Email','loginEmail','email','username')}${label('Password','loginPassword','password','current-password')}${remember('loginRemember')}<button class="primary" type="submit">Sign in</button>${message('loginMessage')}</form><button class="info-link" id="forgotPassword">Forgot password?</button><p>New to Bandstand?</p><button id="showSignup">Create account</button><button class="secondary-close" id="useLocal">Continue without an account</button>`);
 const signup=screen('signupScreen','Create your Bandstand account',`<p class="muted">Save your research sharing choices across devices.</p><form id="signupForm">${label('Email','signupEmail','email','username')}${label('Password · at least 8 characters','signupPassword','password','new-password')}${remember('signupRemember')}<button type="button" class="info-link" id="signupPolicy">Read privacy notice</button><label class="check-label"><input id="signupAgree" type="checkbox" required disabled> I have read the privacy notice.</label><button class="primary" type="submit">Create account</button>${message('signupMessage')}</form><button class="info-link" id="backToLogin">Already have an account? Sign in</button>`);
 const verify=screen('verifyScreen','Check your email',`<p>Enter the confirmation code from your email. If you already confirmed using the email link, return to sign in.</p><form id="verifyForm">${label('Confirmation code','verifyCode','text','one-time-code')}<button class="primary">Confirm email</button>${message('verifyMessage')}</form><button id="verifiedLogin">Return to sign in</button>`);
 const accountDialog=screen('accountSettings','Account',`<p id="accountIdentity"></p><p id="rememberedStatus" class="muted"></p><button id="changePassword">Change password</button><button id="signOut">Sign out</button><button id="deleteAccount" class="danger">Delete my account</button>${message('accountMessage')}`);
 const requestReset=screen('requestResetScreen','Reset your password',`<p>We’ll email a code to verify it’s you.</p><form id="requestResetForm">${label('Email','resetEmail','email','username')}<button class="primary">Send recovery email</button>${message('requestResetMessage')}</form>`);
 const reset=screen('resetScreen','Choose a new password',`<p>Enter the recovery code from your email.</p><form id="resetForm">${label('Recovery code','resetCode','text','one-time-code')}${label('New password','resetPassword','password','new-password')}${label('Repeat new password','resetAgain','password','new-password')}<button class="primary">Save new password</button>${message('resetMessage')}</form>`);
 const deletion=screen('deleteAccountDialog','Delete your account?',`<p>This permanently deletes your cloud account, saved choices, and shared ERP recordings. Local files remain on this computer. Provider backups may retain deleted records until they expire.</p><form id="deleteForm">${label('Type DELETE to confirm','deleteConfirm')}<button class="danger">Permanently delete account</button>${message('deleteMessage')}</form><button id="cancelDelete">Cancel</button>`);
 const privacy=screen('privacyPolicy','Privacy notice',`<p>Recording begins only when you start it. Across-app writing capture may include sensitive text. Stop recording before entering anything you do not want saved. Display redaction does not remove saved text.</p><p>Your writing, EEG, embeddings and personal decoder stay on this computer except for ERP trial data you explicitly select to share. Local files are not encrypted by Bandstand; your computer’s permissions, disk encryption and backups govern access.</p><p>Accounts use Supabase. A remembered session stores a refresh token in macOS Keychain, not your password. Email delivery uses the project’s Gmail SMTP account.</p><p>Shared ERP trials are linked to your account and accessible to project administrators. Other participants cannot access them. Sharing uses standard encryption and access controls, not secure aggregation or differential privacy. You can delete shared ERP copies or your account. Provider backups may retain deleted records according to provider retention.</p><p>Decoder contributions are unavailable. New consent is required before future secure aggregation and participant-level differential privacy are enabled. Deleting contributions cannot automatically erase their influence from a trained model.</p><p>Research contact: Andrew Neff · <a href="mailto:aneff8626@gmail.com">aneff8626@gmail.com</a></p><button id="closePolicy">Back</button>`);
 const choice=(id,title,yes)=>`<label>${title}<select id="${id}"><option value="">Choose…</option><option value="yes">${yes}</option><option value="no">No, keep my data local</option></select></label>`;
 const sharing=screen('sharingSettings','Data Sharing Settings',`<button class="info-link" id="sharingPolicy">Privacy notice</button><form id="sharingForm">${choice('erpConsent','ERP recordings','Yes, allow sharing of selected ERP trials')}<button class="info-link" type="button" id="erpInfo">Details</button><p class="muted">Only recordings you select are uploaded.</p>${choice('decoderInterest','Writing decoder — future training','Yes, I am interested in contributing')}<button class="info-link" type="button" id="decoderInfo">Details</button><p class="muted">Interest only. Decoder uploads remain disabled.</p><button class="primary" id="saveSharing">Save choices</button>${message('sharingMessage')}</form><section><h3>Share a recording</h3><label>Completed ERP recording<select id="shareRecording"><option value="">Select a recording</option></select></label><button id="uploadERP">Share selected recording</button>${message('erpShareStatus')}<h3>Previously shared</h3><div id="sharedRecordings"></div><button id="deleteSharedERP" class="info-link">Delete all shared ERP copies</button></section><button class="secondary-close" id="cancelSharing">Cancel</button>`);
 const erpInfo=screen('erpInfoDialog','ERP sharing details','<p>Supported built-in ERP tasks: visual oddball, auditory oddball, flanker and reward. Shared data contain processed per-channel trial waveforms, trial condition numbers, and relative sample times. Continuous EEG, absolute recording times, custom labels, writing, embeddings and notes are excluded.</p><p>Project administrators can access shared data. Your account links recordings from the same participant. Turning sharing off blocks future uploads; use Delete all shared ERP copies to remove previous uploads.</p>');
 const decoderInfo=screen('decoderInfoDialog','Decoder contributions','<p>This records interest only. Protected shared training is not implemented. No writing, EEG, embeddings or model weights are uploaded. We will request new consent when the implementation and privacy protections are ready.</p>');
 const sharedDeletion=screen('sharedDeletion','Delete shared ERP recordings?','<p>This deletes all ERP copies under your cloud account. Local recordings remain. This cannot be undone in the app.</p><button id="confirmSharedDelete" class="danger">Delete shared copies</button><button id="cancelSharedDelete">Cancel</button>'+message('sharedDeleteMessage'));
 const nav=document.createElement('div');nav.className='account-actions';nav.innerHTML='<button id="accountNav">Account</button><button id="contributeNav">Contribute to research</button>';document.querySelector('aside').append(nav);
 let identity={signed_in:false},settings=await api('enrollment'),verificationEmail='';
 function open(d){if(!d.open)d.showModal()}
 function switchTo(from,to){from.close();open(to)}
 async function refreshIdentity(){identity=await api('account/status');el('accountIdentity').textContent=identity.email||'';el('rememberedStatus').textContent=identity.remembered?'Sign-in remembered in macOS Keychain.':'Sign-in lasts for this app session.';el('accountMessage').textContent=identity.message||'';return identity}
 async function run(form,status,work){if(form.dataset.busy)return;form.dataset.busy='1';const buttons=[...form.querySelectorAll('button')];const disabled=buttons.map(b=>b.disabled);buttons.forEach(b=>b.disabled=true);el(status).textContent='Working…';try{await work()}catch(e){el(status).textContent=e.message}finally{delete form.dataset.busy;buttons.forEach((b,i)=>b.disabled=disabled[i])}}
 const onForm=(id,status,work)=>{el(id).onsubmit=e=>{e.preventDefault();run(el(id),status,work)}};
 function credentials(prefix){return {email:el(prefix+'Email').value.trim(),password:el(prefix+'Password').value,remember:el(prefix+'Remember').checked}}
 el('accountNav').onclick=async()=>{try{await refreshIdentity();open(identity.signed_in?accountDialog:login)}catch(e){open(login);el('loginMessage').textContent=e.message}};
 el('showSignup').onclick=()=>switchTo(login,signup);el('backToLogin').onclick=()=>switchTo(signup,login);el('useLocal').onclick=()=>login.close();
 el('signupPolicy').onclick=()=>{open(privacy);el('signupAgree').disabled=false};el('sharingPolicy').onclick=()=>open(privacy);el('closePolicy').onclick=()=>privacy.close();
 onForm('loginForm','loginMessage',async()=>{identity=await api('account/signin',credentials('login'));el('loginPassword').value='';if(identity.signed_in){login.close();if(identity.message)toast(identity.message)}else el('loginMessage').textContent=identity.message||'Sign-in did not complete.'});
 onForm('signupForm','signupMessage',async()=>{if(!el('signupAgree').checked)throw Error('Read and acknowledge the privacy notice.');const result=await api('account/signup',{...credentials('signup'),policy_version:settings.policy_version,acknowledged:true});verificationEmail=el('signupEmail').value.trim();el('signupPassword').value='';if(result.signed_in){identity=result;signup.close()}else switchTo(signup,verify)});
 onForm('verifyForm','verifyMessage',async()=>{const r=await api('account/confirm',{email:verificationEmail,code:el('verifyCode').value});el('verifyCode').value='';switchTo(verify,login);el('loginEmail').value=verificationEmail;el('loginMessage').textContent=r.message});el('verifiedLogin').onclick=()=>switchTo(verify,login);
 function showReset(){el('resetEmail').value=identity.email||el('loginEmail').value;open(requestReset)}el('forgotPassword').onclick=showReset;el('changePassword').onclick=showReset;
 onForm('requestResetForm','requestResetMessage',async()=>{await api('account/recover',{email:el('resetEmail').value});switchTo(requestReset,reset)});
 onForm('resetForm','resetMessage',async()=>{if(el('resetPassword').value!==el('resetAgain').value)throw Error('Passwords do not match.');const r=await api('account/reset',{email:el('resetEmail').value,code:el('resetCode').value,password:el('resetPassword').value});el('resetForm').reset();identity={signed_in:false};reset.close();accountDialog.close();open(login);el('loginMessage').textContent=r.message});
 el('signOut').onclick=()=>run(accountDialog,'accountMessage',async()=>{await api('account/signout');identity={signed_in:false};accountDialog.close()});
 el('deleteAccount').onclick=()=>{el('deleteConfirm').value='';open(deletion)};el('cancelDelete').onclick=()=>deletion.close();
 onForm('deleteForm','deleteMessage',async()=>{await api('account/delete',{confirmation:el('deleteConfirm').value});identity={signed_in:false};deletion.close();accountDialog.close();toast('Account deleted. Local files were kept.')});
 async function sharedList(){const list=el('sharedRecordings');list.replaceChildren();if(!identity.signed_in||!settings.erp_upload_enabled)return;for(const r of await api('account/erp-list',{})){const p=document.createElement('p');p.className='muted';p.textContent=`${r.protocol} · ${r.trial_count} trials · uploaded ${new Date(r.created_at).toLocaleString()}`;list.append(p)}if(!list.children.length)list.textContent='No shared recordings.'}
 async function openSharing(){open(sharing);el('sharingMessage').textContent='Loading settings…';el('saveSharing').disabled=true;el('uploadERP').disabled=true;el('deleteSharedERP').disabled=true;try{await refreshIdentity();settings=await api('enrollment');const prefs=identity.preferences||{};let allowed=false;if(identity.signed_in&&settings.erp_upload_enabled){const cloud=await api('account/erp-status',{});allowed=cloud.erp_sharing;el('erpConsent').value=prefs.erp_policy==='erp-sharing-v1'?(allowed?'yes':'no'):''}else el('erpConsent').value='';el('decoderInterest').value=prefs.sharing_choices_reviewed?(prefs.decoder_interest_requested?'yes':'no'):'';el('contributeNav').classList.toggle('needs-choice',!prefs.sharing_choices_reviewed);const select=el('shareRecording');select.replaceChildren(new Option('Select a recording',''));for(const r of await api('sessions'))if(r.mode==='erp'&&r.source==='live'&&!r.running&&['oddball','auditory','flanker','reward'].includes(r.protocol))select.add(new Option(`${r.title} · ${new Date(r.started*1000).toLocaleString()}`,r.id));el('uploadERP').disabled=!allowed;el('deleteSharedERP').disabled=!identity.signed_in||!settings.erp_upload_enabled;el('sharingMessage').textContent=!identity.signed_in?'Sign in to save account sharing settings.':!settings.erp_upload_enabled?'ERP sharing is awaiting database activation.':'';await sharedList()}catch(e){el('sharingMessage').textContent=e.message}finally{el('saveSharing').disabled=false}}
 el('contributeNav').onclick=openSharing;el('cancelSharing').onclick=()=>sharing.close();el('erpInfo').onclick=()=>open(erpInfo);el('decoderInfo').onclick=()=>open(decoderInfo);
 onForm('sharingForm','sharingMessage',async()=>{if(!identity.signed_in)throw Error('Sign in before saving data sharing settings.');if(!el('erpConsent').value||!el('decoderInterest').value)throw Error('Choose Yes or No for both categories.');const choices={policy_version:settings.policy_version,acknowledged:true,sharing_choices_reviewed:true,erp_policy:'erp-sharing-v1',erp_sharing_requested:el('erpConsent').value==='yes',decoder_interest_requested:el('decoderInterest').value==='yes'};await api('account/erp-consent',{sharing_policy:'erp-sharing-v1',allow:choices.erp_sharing_requested});await api('account/preferences',choices);await api('enrollment',choices);el('contributeNav').classList.remove('needs-choice');sharing.close();toast('Data sharing settings saved.')});
 el('uploadERP').onclick=()=>run(el('uploadERP').parentElement,'erpShareStatus',async()=>{if(!el('shareRecording').value)throw Error('Select a completed ERP recording.');const r=await api('account/erp-upload',{recording_id:el('shareRecording').value});el('erpShareStatus').textContent=r.message;await sharedList()});
 el('deleteSharedERP').onclick=()=>open(sharedDeletion);el('cancelSharedDelete').onclick=()=>sharedDeletion.close();el('confirmSharedDelete').onclick=()=>run(sharedDeletion,'sharedDeleteMessage',async()=>{await api('account/erp-delete',{confirmation:'DELETE'});sharedDeletion.close();await sharedList();toast('Shared ERP copies deleted. Local recordings remain.')});
 await refreshIdentity();el('contributeNav').classList.toggle('needs-choice',!identity.preferences?.sharing_choices_reviewed);
 if(!identity.signed_in&&!settings.consent.acknowledged)open(login);
}
